petermattis/opttoy

main.go
In the previous version of the code, a node would point to other nodes on the
memo. That meant that if we populated a class in the memo, the nodes pointing to
any of that class's nodes would not see the new alternative plans.
To address that, we now have a tree data type. Following the common terminology
in the literature, we call that type an 'expr'. It isn't an expression,
really. It is a forest of expressions that all share a same root operator on the
memo.  In other words, The 'left' and 'right' pointers out of an 'expr' point to
a memo class.
We still kept the 'node' type around, which is our tree. In a number of
occasions we want to insert or extract a tree from the memo, so that type is
still very useful. Note also that we want to test and apply transformations at
the tree level, …
=> Differentiate between trees and forest.

opttoy2/logic_test.go, opttoy2/opttoy.go, opttoy2/testdata/decorrelate, opttoy2/testdata/prep, opttoy2/testdata/push_down
The single expression tree contains both relational operators (scan,
join, etc) and scalar operators (and, or, plus, minus, variables, etc).
=> opttoy2: construction of unified expression tree

v2/logic_test.go, v2/opttoy.go
Once we got the query into a such a shape we can start the first two steps of
optimization, it is already annotated with everything it needs on those steps.
=> Stopped passing around queryState.

v3/memo.go, v3/pattern.go, v3/xform.go
We define "pattern expression" as the entire pattern tree, which makes
isPatternExpr a misnomer. Renaming to `isPatternLeafOrTree`.
=> improve comments for pattern, rename isPatternExpr

v3/bitmap.go, v3/build.go, v3/decorrelate.go, v3/expr.go, v3/group.go, v3/join.go, v3/join_associativity.go, v3/join_elimination.go, v3/prep.go, v3/project.go, v3/push_down.go, v3/relational_props.go, v3/rename.go, v3/scalar.go, v3/scan.go, v3/set.go, v3/testdata/build, v3/testdata/decorrelate, v3/testdata/group, v3/testdata/infer, v3/testdata/join_elimination, v3/testdata/normalize, v3/testdata/prep, v3/testdata/push_down, v3/testdata/rename, v3/testdata/table, v3/variable.go
This change also helps readability because a lot of direct bit operations are
replaced with properly named function calls.
Depends on https://github.com/cockroachdb/cockroach/pull/20095
I can add the "range compression" to `FastIntSet.String` if you feel strongly about it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/petermattis/opttoy/23)
=> use FastIntSet for bitmaps

v3/group.go, v3/index_join.go, v3/index_scan.go, v3/join.go, v3/memo.go, v3/operator.go, v3/order.go, v3/project.go, v3/relational_props.go, v3/rename.go, v3/scalar.go, v3/scan.go, v3/search.go, v3/select.go, v3/select_to_index_scan.go, v3/set.go, v3/sort.go, v3/testdata/group, v3/testdata/union, v3/variable.go
Previously, logical equivalency for expressions was defined as
equivalent relational properties. But this is too high of a bar to reach
as we need to ensure that the relational properties encode all of the
differences between expressions. Now we invert the default and assume
two expressions are not equivalent without specific handling. In
particular, this change only allows logical equivalency between
expressions when adding transformed expressions back into the memo and
between inner-join expressions (see `memoExpr.groupFingerprint()`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/petermattis/opttoy/27)
=> Adjust logical equivalency for expressions

v3/TODO, v3/expr.go, v3/group.go, v3/index_join.go, v3/index_scan.go, v3/join.go, v3/logic_test.go, v3/memo.go, v3/operator.go, v3/order.go, v3/project.go, v3/rename.go, v3/scalar.go, v3/scan.go, v3/search.go, v3/select.go, v3/set.go, v3/sort.go, v3/testdata/index_scan, v3/testdata/order, v3/variable.go
Allow operators to indicate whether they are logical or physical. Only
physical expressions are costed.
Add memoOptState which tracks the optimization state for a particular
optimization context (required physical properties) within a group. Add
a per-group map from optimization context to optimization state.
Add extremely basic costing. Lots of TODOs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/petermattis/opttoy/29)
=> Initial work on costing

v3/build.go, v3/index_scan.go, v3/planner.go, v3/relational_props.go, v3/stats.go, v3/table.go
We have a bunch of places where we're using a string (e.g. as a map key) and
it's not immediately obvious what the string is. This commit adds a new type for
table names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/petermattis/opttoy/32)
=> add tableName, columnName

v3/TODO, v3/search.go, v3/testdata/order
For operators which pass through the ordering of their children (select
and project), create a new expression containing the passed through
ordering.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/petermattis/opttoy/33)
=> Make pass through orderings more explicit

v3/build.go, v3/push_down.go, v3/scalar_props.go
Remove definedCols which was only needed for projections, but that info
was also available in relationalProps.columns. Remove containsSubquery
which was never used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/petermattis/opttoy/36)
=> Simplify scalarProps

v3/join_associativity.go, v3/join_commutativity.go, v3/join_elimination.go, v3/prep.go, v3/scan_to_index_scan.go, v3/search.go, v3/select_to_index_scan.go, v3/xform.go
All of the existing check() methods were returning true. And there isn't
currently a useful reason for performing any work in check() vs
apply(). We can always re-add if the need arises.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/petermattis/opttoy/37)
=> Remove the xform.check() method

v3/build.go, v3/relational_props.go, v3/testdata/build, v3/testdata/push_down
Previously, the output cols for a scan of a table were the same for
every time the table was referenced in a query. But that causes badness
for pushing down filters in self-joins such as:
SELECT * FROM a AS l JOIN a AS r ON (l.x = r.y)
For this query, `l.x` is not equivalent to `r.x` and `l.y` is not
equivalent to `r.y`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/petermattis/opttoy/38)
=> Every scan generates a new set of output cols

v3/planner.go, v3/stats.go, v3/testdata/stats
Add functions to filter a histogram given a predicate such as
x < 4, in which the column is compared to a constant with a
scalar operator.  The new functions filter the histogram for
the operators ltOp, leOp, gtOp and geOp. The result is a histogram
which essentially has a subset of the buckets in the original
histogram. There is some complexity if the constant in the predicate
falls in the middle of a bucket, because then the bucket
must be split into two buckets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/petermattis/opttoy/35)
=> Add functions to filter a histogram

v3/apply.go, v3/expr.go, v3/group.go, v3/index_scan.go, v3/join.go, v3/memo.go, v3/operator.go, v3/order.go, v3/project.go, v3/scalar.go, v3/scan.go, v3/search.go, v3/select.go, v3/set.go, v3/sort.go, v3/variable.go
scalar -> scalarClass
join -> joinClass
etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/petermattis/opttoy/41)
=> rename operatorInfo and related names

v3/prep.go, v3/push_down.go
Remove the hack to perform outputCols propagation after pushing down
filters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/petermattis/opttoy/40)
=> Fix pushDownFilters to maintain the outputCols property

v3/stats.go, v3/testdata/stats
Add functions to filter a histogram for the operators
eqOp, neOp, inOp and notInOp. These operators correspond
to predicates such as x = 4, x != 4, x in (4, 5, 6) and
x not in (4, 5, 6). The result of these new functions
is a histogram including only the valuse that satisfy
the predicate.
cc @RaduBerinde
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/petermattis/opttoy/42)
=> Add more functions to filter a histogram

v3/scope.go, v3/testdata/subquery
The rules now support a strict superset of queries supported by
Postgres.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/petermattis/opttoy/50)
=> Simplify subquery typing rules

v3/stats.go, v3/testdata/stats
This commit continues the work to enable maintenance of
histograms throughout the query tree.  Given two filtered
histograms on the same column, they can now be combined to
support expressions with an AND or OR operation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/petermattis/opttoy/51)
=> Add functions to combine two histograms with andOp or orOp

v4/build/builder.go, v4/build/column_props.go, v4/build/scope.go, v4/opt/factory.go, v4/opt/factory.og.go, v4/opt/norm/filter.opt, v4/opt/norm/norm.opt, v4/testdata/decorrelate, v4/testdata/normalize, v4/testdata/push_down
This PR makes a few small updates to the transformation logic
in the `v4` version of opttoy:
1. Normalize comparison expressions so the variable is always on
the left.  E.g., `5 > x` -> `x < 5`. This was already the case for
equals and not-equals (= and !=), but this commit adds the
inequalities <, <=, >, and >=.
2. Infer filters on equivalent columns. For example, if two columns
x and y are equal, and there is already a filter on `x` (e.g. `x < 5`),
then an additional filter is added for `y` (`y < 5`).
3. Fix the push-down logic so that multiple filters on the same table
get pushed down to the same subquery. Previously, a new subquery was
created for each pushed-down filter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Add filter inference, normalization and push-down logic to v4

v4/build/builder.go, v4/build/scope.go, v4/opt/factory.og.go, v4/opt/memo.go, v4/opt/norm/push_down.opt, v4/testdata/push_down
This commit adds a simple pattern to push a filter onto an
inner join if it can't be pushed below. This is going to be
important for queries where the `ON` condition isn't explicitly
specified. For example, `SELECT * FROM a, b WHERE a.x = b.x`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/petermattis/opttoy/55)
=> Push filters onto inner joins
